name: Surge-Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          npm i
          npm run build
      - name: Surge Setup
        run: npm install -g surge
      - name: Deploy
        run: surge ./build https://shery-shoe-store.surge.sh --token ${{secrets.SURGE_TOKEN}}
